apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: gitops-demo
        image: hrittik/gitops:latest
        ports:
        - containerPort: 3112
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-gitops-service
spec:
  selector:
    app: gitops-demo
  ports:
    - port: 3112
      targetPort: 3112
  type: LoadBalancer
