apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-ops-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo-main
  template:
    metadata:
      labels:
        app: gitops-demo-main
    spec:
      containers:
      - name: gitops-demo-main
        image: mauu/gitops-main:.*
        ports:
        - containerPort: 3112
