apiVersion: apps/v1
kind: Deployment
metadata:
  name: midori-ops-main
  namespace: midori
spec:
  replicas: 1
  selector:
    matchLabels:
      app: midori-ops-main
  template:
    metadata:
      labels:
        app: midori-ops-main
    spec:
      containers:
      - name: midori-ops-main
        image: mauu/gitops-main:v11
        ports:
        - containerPort: 3112
