apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
      - name: gitops-demo
        image: mauu/gitops-main:latest
        ports:
        - containerPort: 3112
