apiVersion: apps/v1
kind: Deployment
metadata:
  name: portainer-ops-develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo-develop
  template:
    metadata:
      labels:
        app: gitops-demo-develop
    spec:
      containers:
      - name: gitops-demo-develop
        image: mauu/gitops-develop:latest
        ports:
        - containerPort: 3111
